import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Libre_Bodoni } from 'next/font/google'
import { Nunito_Sans } from "next/font/google";

const libre_Bodoni = Libre_Bodoni({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-Libre_Bodoni',
})

const nunito_Sans = Nunito_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-Nunito_Sans',
})


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito_Sans.variable} ${libre_Bodoni.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
